# RESTBase config

port: 7231

# System domain (used to store restbase metadata)
sysdomain: restbase.local

templates:

  wmf-content-1.0.0: &wp/content/1.0.0
    swagger: '2.0'
    # swagger options, overriding the shared ones from the merged specs (?)
    info:
      version: 1.0.0-abcd
      title: Standard Wikimedia content API
      description: All the content for this domain.
      termsOfService: http://wikimedia.org/terms/
      contact:
        name: The project maintainers
        url: http://mediawiki.org/wiki/RESTBase
      license:
        name: Creative Commons 4.0 International
        url: http://creativecommons.org/licenses/by/4.0/
    security:
      # ACLs for public *.wikipedia.org wikis
      - mediaWikiAuth:
        - user:read
    paths:
      /v1:
        x-restbase:
          specs:
            - mediawiki/v1/content
          # - mediawiki/v1/mobile
          # - mediawiki/v1/revision-scoring
          modules:
            - name: dummy-mod
              version: 0.0.1
              type: file
              path: dummy
              options:
                dummyarg: foobar

    x-restbase-paths: # Internal paths. These use the same config structure as
                      # regular paths, but are restricted to internal use and
                      # don't show up in swagger.
                      #
                      # This stanza defines the /{domain}/sys/ hierarchy.

      /sys/table: &wp/sys/table # Can use this anchor to share the table
                                # backend even if other parts differ
        x-restbase:
          specs:
            - restbase/sys/table
#          modules:
#            # There can be multiple modules too per stanza, as long as the
#            # exported symbols don't conflict. The operationIds from the spec
#            # will be resolved against all of the modules.
#            - name: restbase-cassandra
#              version: 1.0.0
#              type: npm
#              options: # Passed to the module constructor
#                hosts: [localhost]
#                keyspace: system
#                username: cassandra
#                password: cassandra
#                defaultConsistency: localQuorum # or 'one' for single-node testing

      /sys/page_revisions: &wp-page-revisions
        x-restbase:
          specs:
            - mediawiki/sys/page_revisions
#          modules:
#            - name: restbase-mod-page_revisions
#              version: 1.0.0
#              type: npm
#              options:
#                apiURL: http://{domain}/w/api.php

      /sys/key_rev_value: &wp/sys/key_rev_value
        x-restbase:
          specs:
            - restbase/sys/key_rev_value
#          modules:
#            - name: restbase-mod-key_rev_value
#              version: 1.0.0
#              type: npm

      /sys/parsoid:
        x-restbase:
          specs:
            - mediawiki/sys/parsoid
#          modules:
#            - name: restbase-mod-parsoid
#              version: 1.0.0
#              type: npm
#              options:
#                parsoidHost: http://parsoid-lb.wikimedia.org
#                apiURL: http://{domain}/w/api.php
          resources:
            # Storage owned by this module. Created / checked after setting up
            # all modules (separate traversal).
            # Convention: Prefix each entry with the owning sys path to avoid
            # conflicts.
            - uri: /{domain}/sys/key_rev_value/parsoid.html
            - uri: /{domain}/sys/key_rev_value/parsoid.data-parsoid
            - uri: /{domain}/sys/key_rev_value/parsoid.data-mw
            - uri: /{domain}/sys/key_rev_value/parsoid.wikitext

#      /sys/revscore:
#        title: Simple revscore service wrapper
#        x-restbase:
#          # Generic revision service interface; Expects requests of the form
#          # /{title}/{revision}.
#          # Specific interface documentation (content types etc) at public
#          # entry point, although we might also want to enforce them
#          # internally.
#          specs:
#            - restbase/sys/key_rev_service
#          modules:
#            - name: restbase-mod-service
#              version: 1.0.0 # simple service module, to be shared
#              options:
#                storage:
#                  uri: /{domain}/sys/key_rev_value/revscore.scores/{title}/{revision}
#                service: 
#                  uri: http://revscore.wikimedia.org/{domain}/{title}/{revision}
#          resources:
#            - uri: /{domain}/sys/key_rev_value/revscore.scores

  wp-default-1.0.0: &wp/default/1.0.0
    x-restbase: 
      specs:
        - *wp/content/1.0.0
                  


spec:
  title: "The RESTBase root"
  # Some more general RESTBase info
  paths:
    /{domain:en.wikipedia.org}: *wp/default/1.0.0
    /{domain:de.wikipedia.org}: *wp/default/1.0.0
    /{domain:es.wikipedia.org}: *wp/default/1.0.0
    /{domain:nl.wikipedia.org}: *wp/default/1.0.0


logging:
  name: restbase
  #streams:
  ## XXX: Use gelf-stream -> logstash
  #- type: gelf
  #  host: <%= @logstash_host %>
  #  port: <%= @logstash_port %>

monitoring:
    # statsdHost: localhost
