# RESTBase wikimedia example config

# Load some project templates. These are referenced / shared between domains
# in the root_spec further down.
default_project: &default_project
  x-modules:
    /:
      - path: projects/wmf_default.yaml
        options: &default_options
          table:
            hosts: [localhost]
            keyspace: system
            username: cassandra
            password: cassandra
            defaultConsistency: one # or 'localQuorum' for production
            storage_groups:
              - name: default.group.local
                domains: /./
          parsoid:
            host: http://parsoid-beta.wmflabs.org
          action:
            apiUriTemplate: "{{'https://{domain}/w/api.php'}}"
          graphoid:
            host: http://graphoid.wikimedia.org
          mathoid:
            host: http://mathoid-tester.wmflabs.org
            # 10 days Varnish caching, one day client-side
            cache-control: s-maxage=864000, max-age=86400
          mobileapps:
            host: http://appservice.wmflabs.org

# A different project template, sharing configuration options.
wikimedia.org: &wikimedia.org
  x-modules:
    /:
      - path: projects/wikimedia.org.yaml
        options: *default_options

wiktionary_project: &wiktionary_project
  x-modules:
    /:
      - path: projects/wmf_wiktionary.yaml
        options: *default_options

# The root of the spec tree. Domains tend to share specs by referencing them
# using YAML references.
spec_root: &spec_root
  title: "The RESTBase root"
  paths:
    /{domain:en.wikipedia.org}: *default_project
    /{domain:fr.wikipedia.org}: *default_project
    /{domain:de.wikipedia.org}: *default_project
    /{domain:es.wikipedia.org}: *default_project
    /{domain:it.wikipedia.org}: *default_project
    /{domain:da.wikipedia.org}: *default_project
    /{domain:sv.wikipedia.org}: *default_project

    # Example for wiktionary
    /{domain:en.wiktionary.org}: *wiktionary_project

    # global domain
    /{domain:wikimedia.org}: *wikimedia.org

    # A robots.txt to make sure that the content isn't indexed.
    /robots.txt:
      get:
        x-request-handler:
          - static:
              return:
                status: 200
                headers:
                  content-type: text/plain
                body: |
                  User-agent: *
                  Allow: /*/v1/?doc
                  Disallow: /

# Finally, a standard service-runner config.
info:
  name: restbase

services:
  - name: restbase
    module: hyperswitch
    conf: 
      port: 7231
      spec: *spec_root
      salt: secret
      default_page_size: 125
      user_agent: RESTBase

logging:
  name: restbase
  level: info
  #streams:
  #- type: gelf
  #  host: <%= @logstash_host %>
  #  port: <%= @logstash_port %>

metrics:
  #type: txstatsd
  #host: localhost
  #port: 8125
  #batch: true